apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  service:
    type: NodePort
  rabbitmq:
      additionalPlugins:
        - rabbitmq_mqtt
